# Generated by Django 3.1.7 on 2021-03-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='usertype',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=50),
        ),
    ]
